routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('dashboard');
// });
Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

Route::get('/monitor', [App\Http\Controllers\MonitorController::class, 'index'])->name('monitor');

Route::get('/graphic', [App\Http\Controllers\GraphicController::class, 'index'])->name('graphic');

Route::get('/user', [App\Http\Controllers\UserController::class, 'index'])->name('user');

Route::get('/user/delete', [App\Http\Controllers\DeleteController::class, 'index'])->name('user.delete');

Route::get('/user/edit', [App\Http\Controllers\EditController::class, 'index'])->name('user.edit');

Route::get('/user/admin', [App\Http\Controllers\AddAdminController::class, 'index'])->name('user.admin');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
// function () {
//     $id = Auth::id();
//     $loggedin = User::find($id);
//     return view('dashboard', ['loggedin' => $loggedin]);
// }
Route::get('/sensor/export', [App\Http\Controllers\ExportSensorController::class, 'index'])->name('sensor.export') ;

Route::get('/sensor/import', [App\Http\Controllers\ImportSensorController::class, 'show'])->name('sensor.import.show') ;

Route::post('/sensor/import', [App\Http\Controllers\ImportSensorController::class, 'index'])->name('sensor.import') ;

Route::get('/sensor/setstatus/{id}/{status}', [App\Http\Controllers\StatusController::class, 'setSensorStatus'])->name('sensor.status') ;

Auth::routes();

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@extends('adminlte::page', ['loggedin' => $loggedin])

@section('title', 'Dashboard')

@section('content_header')
<div class='card'>
<div class='card-header bg-primary'><b><i class="fas fa-satellite-dish"></i></b> Real Time Monitoring</div>
</div>
@stop

@section('content')

<div class='card'>
    <div class='card-body bg-light border'>
        <table class='table table-striped table-hover table-bordered mb-sm-3'>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Sensor 1</th>
                    <th>Sensor 2</th>
                    <th>Sensor 3</th>
                    <th>Sensor 4</th>
                </tr>
            </thead>
            <tbody class='sensorTable'>
                <div class="">
                    <!-- <tr>
                        <td>No</td>
                        <td>Sensor 1</td>
                        <td>Sensor 2</td>
                        <td>Sensor 3</td>
                        <td>Sensor 4</td>
                        <td>Sensor 5</td>
                    </tr> -->
                </div>
            </tbody>
        </table>
        
    </div>
    @if ($loggedin->level == 'admin')
    <div class='card-footer border' style='background-color:#f7f7f7'>
        @if (session('status'))
            <div class="alert alert-success my-3" role='alert'>
                {{ session('status') }}
            </div>
        @endif
        <div class="card-columns">
        @forelse($sensorstatus as $sensor)
            <div class='card bg-light align-items-center'>
                <div class='card-header'>
                    {{$sensor->name}}
                    <button class="btn btn-sm btn-primary float-right disabled">
                        {{ $sensor->status == 1 ? 'On' : 'Off' }}
                    </button>
                </div>
                <div class='card-body'>
                    <div class="btn-group">
                        <a type='button' href="{{ route('sensor.status', [$sensor->id, '1']) }}" class='btn btn-success'>ON</a>
                        <a type='button' href="{{ route('sensor.status', [$sensor->id, '0']) }}" class='btn btn-warning'>OFF</a>
                    </div>
                </div>
            </div>
        @empty
            <div class="alert alert-warning my-3" role='alert'>
                Status Table is Empty
            </div>
        @endforelse
            
        </div>
    </div>
    @endif
</div>
@stop

@section('css')
    
@stop

@section('js')
    
<script>
  var data
  var updateData = function() {
    $.post("{{ route('syncExcel') }}") ;
    $.ajax({
      url: "{{ route('fetchData') }}",
      type: 'GET',
      dataType: 'json',
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      },
      success: function(data) {

        var resultTag = "" ;
        var i = 0 ;
        var len = data.length ;
        
        $.each(data, function(){
            var j = len-i ;
            resultTag += 
            "<tr>" +
                "<td>" + j + "</td>" +
                "<td>" + data[i]['sensor1'].toFixed(2) + "</td>" +
                "<td>" + data[i]['sensor2'].toFixed(2) + "</td>" +
                "<td>" + data[i]['sensor3'].toFixed(2) + "</td>" +
                "<td>" + data[i]['sensor4'].toFixed(2) + "</td>" +
            "</tr>"
            i += 1 ;
        }) ;
        $('.sensorTable').html(resultTag) ;
      },
      error: function(data){
        console.log(data);
      }
    });
  }
  
  updateData();
  setInterval(() => {
    updateData();
  }, 5000);
</script>
@stop

resources/views/graphic.blade.php
@extends('adminlte::page', ['loggedin' => $loggedin])

@section('title', 'Graphic')

@section('content_header')
    
<div class='card'>
<div class='card-header bg-primary'><b><i class="fas fa-chart-line"></i></b> Chart</div>
</div>

@stop

@section('content')
    
<div class='card'>
    <div class='card-body'>
        <div id='chartku'></div>
    </div>
</div>

@stop

@section('css')
    
@stop

@section('js')
    
@stop

@section('graphicjs')
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js"></script>
<script>
    var header = ['TimeStamp', 'Arus (A)', 'Tegangan (V)', 'Getaran (Hz)', 'Thermocouple (C)'] ;
    var data, i, ds, first ;

    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
      $.post("{{ route('syncExcel') }}") ;
      $.get("{{ route('getGraphicData') }}", function(req){
        i = 1 ;
        data = [] ;
        data.push(header) ;
        
        $.each(req.reverse(), function(key, value) {
          
          data.push(Object.values(value)) ;

          if (i == 1) {
            first = new Date(data[i][0]) ;
          }
          // console.log(data[i][0]) ;
          ds = new Date(data[i][0]) ;
          // console.log(ds) ;
          data[i][0] = ds.toLocaleString('en-IN') ;
          i++ ;
        }) ;
        console.log(data) ;
        var dataChart = google.visualization.arrayToDataTable(data);

        var options = {
          title: 'Grafik Perubahan Data (' + first.toDateString() + ')' ,
          // curveType: 'function',
          height:500,
          legend: { position: 'bottom' },
          series: {
                0: { pointShape: 'circle' },
                1: { pointShape: 'triangle' },
                2: { pointShape: 'square' },
                3: { pointShape: 'diamond' },
                4: { pointShape: 'star' },
                5: { pointShape: 'polygon' }
          }
        };

        var chart = new google.visualization.LineChart(document.getElementById('chartku'));

        chart.draw(dataChart, options);
      }) ;
    }
    setInterval(() => {
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
    }, 5000);
</script>
@stop

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    
Dashboard

@stop

@section('content')
    
Welcome to this beautiful admin panel.


@stop

@section('css')
    
@stop

@section('js')
    
@stop

resources/views/monitor.blade.php
@extends('adminlte::page', ['loggedin' => $loggedin])

@section('title', 'Monitoring')

@section('content_header')
    
<div class='card'>
<div class='card-header bg-primary'><b><i class="fas fa-satellite-dish"></i></b> Real Time Monitoring</div>
</div>

@stop

@section('content')
    
<div class='card'>
    <div class='card-header border'>
        <i class="fas fa-download"></i> Export PDF
    </div>
    <div class='card-body border'>
        <form action='/sensor/export' method='get'>
            <div class="container p-3">
                <label>Tanggal Awal</label>
                <input class="form-control mb-5" id='datepicker' type="text" name='tglawal' autocomplete='off' required>
                <label>Tanggal Akhir</label>
                <input class="form-control mb-3" id='datepicker2' type="text" name='tglakhir' autocomplete='off' required>
                <button class='btn btn-primary' type='submit'>Export</button>
            </div>
        </form>
    </div>
    <div class='card-footer border'>

    </div>
</div>
<!-- @if ($loggedin->level == 'admin')
<div class='card'>
    <div class='card-header border'>
        <i class="fas fa-upload"></i> Import Excel
    </div>
    <div class='card-body border'>
        @if (session('status'))
            <div class="alert alert-success mt-3" role='alert'>
                {{ session('status') }}
            </div>
        @endif
        <form action="{{ route('sensor.import') }}" method='post' enctype='multipart/form-data'>
        @csrf
            <div class="container p-3">
                <div class="custom-file mb-3">
                    <input type="file" name='excelFile' class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
                
                <button class='btn btn-primary' type='submit'>Import</button>
            </div>
        </form>
    </div>
    <div class='card-footer border'>

    </div>
</div>
@endif -->
@stop

@section('css')
    
@stop

@section('js')
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
      $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
  } );

  $( function() {
      $( "#datepicker2" ).datepicker({ dateFormat: 'yy-mm-dd' });
  } );

  $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
  });

  var sync = function() {
    $.post("{{ route('syncExcel') }}") ;
  }
  setInterval(() => {
    sync();
  }, 5000);
</script>
@stop

resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-jet-application-mark class="block h-9 w-auto" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                </div>
            </div>

            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="ml-3 relative">
                        <x-jet-dropdown align="right" width="60">
                            <x-slot name="trigger">
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition">
                                        {{ Auth::user()->currentTeam->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            </x-slot>

                            <x-slot name="content">
                                <div class="w-60">
                                    <!-- Team Management -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Manage Team') }}
                                    </div>

                                    <!-- Team Settings -->
                                    <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                        {{ __('Team Settings') }}
                                    </x-jet-dropdown-link>

                                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                        <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                            {{ __('Create New Team') }}
                                        </x-jet-dropdown-link>
                                    @endcan

                                    <div class="border-t border-gray-100"></div>

                                    <!-- Team Switcher -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Switch Teams') }}
                                    </div>

                                    @foreach (Auth::user()->allTeams() as $team)
                                        <x-jet-switchable-team :team="$team" />
                                    @endforeach
                                </div>
                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                @endif

                <!-- Settings Dropdown -->
                <div class="ml-3 relative">
                    <x-jet-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition">
                                    <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition">
                                        {{ Auth::user()->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            @endif
                        </x-slot>

                        <x-slot name="content">
                            <!-- Account Management -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Account') }}
                            </div>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Profile') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <div class="border-t border-gray-100"></div>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                </div>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                    <div class="flex-shrink-0 mr-3">
                        <img class="h-10 w-10 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                    </div>
                @endif

                <div>
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                    this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                        <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                            {{ __('Create New Team') }}
                        </x-jet-responsive-nav-link>
                    @endcan

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/user.blade.php
@extends('adminlte::page', ['loggedin' => $loggedin])

@section('title', 'User')

@section('content_header')
    
<div class='card'>
<div class='card-header bg-primary'><b><i class="fas fa-user"></i></b> Users</div>
</div>

@stop

@section('content')
    
<div class='card'>
    <div class='card-body bg-light border'>
        <table class='table table-striped table-hover table-bordered mb-sm-3'>
            <thead>
                <tr class='text-center'>
                    <th>Nama</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            @forelse($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->level }}</td>
                    <td>
                        <div class='col-sm text-center'>
                            <div class="btn-group">
                                @if ($user->level == 'user' || $loggedin->id == $user->id)
                                    @if ($user->level == 'user')
                                        <button type="button" id='modalKu' data-id='{{ $user->id }}' data-toggle="modal" data-target="#modalA" class="addAdmin btn btn-sm btn-success">+Admin</button>
                                    @endif
                                    <button type="button" id='modalKu' data-id='{{ $user->id }}' data-toggle="modal" data-target="#modalE" class="editUser btn btn-sm btn-primary">Edit</button>
                                    <button type="button" id='modalKu' data-id='{{ $user->id }}' data-toggle="modal" data-target="#modalC" class="deleteUser btn btn-sm btn-danger">Remove</button>
                                @endif
                            </div>
                        </div>
                    </td>
                </tr>
            @empty
                <div class="alert alert-danger">
                    Tidak ada user.
                </div>
            @endforelse
            </tbody>
        </table>
        <div class='d-flex justify-content-center'>
            {!! $users->links() !!}
        </div>
    </div>
</div>

<div class="modal fade" id="modalC">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">Konfirmasi</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body">
        Apakah anda yakin?
      </div>

      <div class="modal-footer">
        <form action='/user/delete' method='get' id='formKu'>
            
            <input type='hidden' id='id1' name='id'>
            <button type="submit" class="btn btn-danger">Hapus</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Kembali</button>
        </form>
      </div>

    </div>
  </div>
</div>

<div class="modal fade" id="modalA">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">Konfirmasi</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body">
        Apakah anda yakin?
      </div>

      <div class="modal-footer">
        <form action='/user/admin' method='get' id='formKu3'>
            
            <input type='hidden' id='id3' name='id'>
            <input type='hidden' name='role' value='admin'>
            <button type="submit" class="btn btn-success">Ya</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Kembali</button>
        </form>
      </div>

    </div>
  </div>
</div>

<div class="modal fade" id="modalE">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">Ubah Identitas</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

        <form action='/user/edit' method='get' id='formKu2'>
            <div class="modal-body">
                <label for="nama">Nama Lengkap:</label>
                <input type="text" class="form-control" id="nama" name='nama' required>
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name='email' required>
            </div>

            <div class="modal-footer">
                    
                    <input type='hidden' id='id2' name='id'>
                    <button type="submit" class="btn btn-success">Simpan</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Kembali</button>
            </div>
        </form>

    </div>
  </div>
</div>

@stop

@section('css')
    
@stop

@section('js')

@stop

@section('graphicjs')
<script>
    $(document).on('click','.deleteUser',function(){
         let id = $(this).attr('data-id');
         $('#id1').val(id);
    });

    $(document).on('click','.editUser',function(){
         let id = $(this).attr('data-id');
         $('#id2').val(id);
    });

    $(document).on('click','.addAdmin',function(){
         let id = $(this).attr('data-id');
         $('#id3').val(id);
    });
</script>
@stop